steps:
  - id: "Depend Services"
    name: "gcr.io/$PROJECT_ID/cloud-builders/docker-compose"
    args: ["up", "-d"]
  - id: "Test"
    name: "gcr.io/$PROJECT_ID/cloud-builders/pytest"
    args: ["pytest", "-v", "-s"]
    env:
      - DEBUG=0
      - DATABASE_USER=docker
      - DATABASE_NAME=docker
      - DATABASE_USER=docker
      - DATABASE_PASSWORD=docker
      - DATABASE_HOST=postgres
      - GS_PROJECT_ID=$PROJECT_ID
      - GS_BUCKET_NAME=$PROJECT_ID-$BRANCH_NAME
  - id: "Build Image"
    name: "gcr.io/kaniko-project/executor"
    args:
      - --destination=gcr.io/$PROJECT_ID/django-startproject/app:$COMMIT_SHA
  # - id: "Deploy"
  #   name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "beta"
  #     - "run"
  #     - "deploy"
  #     - "django-startproject"
  #     - "--allow-unauthenticated"
  #     - "--platform"
  #     - "managed"
  #     - "--project"
  #     - "$PROJECT_ID"
  #     - "--image"
  #     - "gcr.io/$PROJECT_ID/django-startproject/app:$COMMIT_SHA"
  #     - "--region"
  #     - "asia-northeast1"
timeout: 900s
